email:
  login: suporte@dclick.com.br
  password: vanxhewjbhhuyoly
  #receivers: lucas.rodrigues@dclick.com.br,leonardo.buzim@dclick.com.br
  receivers: leonardo.buzim@dclick.com.br, gerenciafinanceira@oceanica.com.br
  #receivers: leonardo.buzim@dclick.com.br

logLevel: 20

mes:
  1: 01 - Janeiro
  2: 02 - Fevereiro
  3: 03 - Março
  4: 04 - Abril
  5: 05 - Maio
  6: 06 - Junho
  7: 07 - Julho
  8: 08 - Agosto
  9: 09 - Setembro
  10: 10 - Outubro
  11: 11 - Novembro
  12: 12 - Dezembro
